name: your_doctor_app_flutter
description: A new Flutter project for Your Doctor app.

publish_to: 'none' # Remove this line if you intend to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # تأكد أن هذا يتوافق مع إصدار Flutter لديك

dependencies:
  flutter:
    sdk: flutter
  
  # HTTP client for making API requests
  http: ^1.2.1
  
  # State management solution
  provider: ^6.1.2
  
  # For persisting user token and other sensitive data
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.0.0 # لتخزين الرموز المميزة بشكل آمن
  
  # For date and time formatting
  intl: ^0.19.0
  
  # For displaying icons (optional, but good for UI)
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # To add assets to your application
  # assets:
  #   - assets/images/
  #   - assets/icons/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font.
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro_Bold.ttf